<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus UFT One" productVer="2021" os="Windows 10" host="vm001"><DocLocation><![CDATA[C:\Users\sfjbs\Desktop\opencart\DataDrivenFramework\Driver\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus UFT One"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[Res63]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Mod_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Mod_2" started.]]></Details>
<Time><![CDATA[4/7/2022 - 15:53:46]]></Time>
<TimeTick>1649327026</TimeTick>
<NodeArgs eType="Transaction" icon="4" nRep="7" nType="Start Transaction" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Mod_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/7/2022 - 15:53:50]]></Time>
<TimeTick>1649327030</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Details>
<Time><![CDATA[4/7/2022 - 15:53:50]]></Time>
<TimeTick>1649327030</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/7/2022 - 15:54:11]]></Time>
<TimeTick>1649327051</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Your Store.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://demo.opencart.com/<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[4/7/2022 - 15:54:11]]></Time>
<TimeTick>1649327051</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" >
<Disp><![CDATA[Your Store.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/7/2022 - 15:54:16]]></Time>
<TimeTick>1649327056</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[iPhone 6.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:54:16]]></Time>
<TimeTick>1649327056</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" >
<Disp><![CDATA[iPhone 6.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="16" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/7/2022 - 15:54:17]]></Time>
<TimeTick>1649327057</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:54:17]]></Time>
<TimeTick>1649327057</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="21" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/7/2022 - 15:54:26]]></Time>
<TimeTick>1649327066</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="22" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="20" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="13" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Slideshow1]]></Obj>
<Details ><![CDATA[Navigation Successful]]></Details>
<Time><![CDATA[4/7/2022 - 15:54:26]]></Time>
<TimeTick>1649327066</TimeTick>
<NodeArgs eType="User" icon="9" nRep="23" status="Passed" >
<Disp><![CDATA[Slideshow1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/7/2022 - 15:54:26]]></Time>
<TimeTick>1649327066</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Your Store.Back]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:54:26]]></Time>
<TimeTick>1649327066</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="26" >
<Disp><![CDATA[Your Store.Back]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Your Store.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:54:30]]></Time>
<TimeTick>1649327070</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="28" >
<Disp><![CDATA[Your Store.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/7/2022 - 15:54:39]]></Time>
<TimeTick>1649327079</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Details>
<Time><![CDATA[4/7/2022 - 15:54:39]]></Time>
<TimeTick>1649327079</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="32" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="31" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Your Store.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://demo.opencart.com/<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[4/7/2022 - 15:54:59]]></Time>
<TimeTick>1649327099</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="34" >
<Disp><![CDATA[Your Store.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:03]]></Time>
<TimeTick>1649327103</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[WebElement_3.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:03]]></Time>
<TimeTick>1649327103</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="37" >
<Disp><![CDATA[WebElement_3.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[WebElement_4.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:04]]></Time>
<TimeTick>1649327104</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="39" >
<Disp><![CDATA[WebElement_4.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="36" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Your Store.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:05]]></Time>
<TimeTick>1649327105</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="41" >
<Disp><![CDATA[Your Store.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:11]]></Time>
<TimeTick>1649327111</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:11]]></Time>
<TimeTick>1649327111</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="45" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="44" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Your Store.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://demo.opencart.com/<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:31]]></Time>
<TimeTick>1649327131</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="47" >
<Disp><![CDATA[Your Store.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:34]]></Time>
<TimeTick>1649327134</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[MacBook.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:34]]></Time>
<TimeTick>1649327134</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="50" >
<Disp><![CDATA[MacBook.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="49" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:38]]></Time>
<TimeTick>1649327138</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:38]]></Time>
<TimeTick>1649327138</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="54" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:39]]></Time>
<TimeTick>1649327139</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="55" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="53" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="25" status="Passed" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA[Featured]]></Obj>
<Details ><![CDATA[Featured slide1 Successful]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:39]]></Time>
<TimeTick>1649327139</TimeTick>
<NodeArgs eType="User" icon="9" nRep="56" status="Passed" >
<Disp><![CDATA[Featured]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:39]]></Time>
<TimeTick>1649327139</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Your Store.Back]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:39]]></Time>
<TimeTick>1649327139</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="59" >
<Disp><![CDATA[Your Store.Back]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:44]]></Time>
<TimeTick>1649327144</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[iPhone.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:44]]></Time>
<TimeTick>1649327144</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="62" >
<Disp><![CDATA[iPhone.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="61" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:49]]></Time>
<TimeTick>1649327149</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:49]]></Time>
<TimeTick>1649327149</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="66" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:49]]></Time>
<TimeTick>1649327149</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="67" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="65" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="58" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[Featured]]></Obj>
<Details ><![CDATA[Featured slide2 Successful]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:49]]></Time>
<TimeTick>1649327149</TimeTick>
<NodeArgs eType="User" icon="9" nRep="68" status="Passed" >
<Disp><![CDATA[Featured]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:49]]></Time>
<TimeTick>1649327149</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Your Store.Back]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:49]]></Time>
<TimeTick>1649327149</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="71" >
<Disp><![CDATA[Your Store.Back]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:54]]></Time>
<TimeTick>1649327154</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Apple Cinema 30'.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:54]]></Time>
<TimeTick>1649327154</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="74" >
<Disp><![CDATA[Apple Cinema 30'.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="73" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:58]]></Time>
<TimeTick>1649327158</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:58]]></Time>
<TimeTick>1649327158</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="78" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:58]]></Time>
<TimeTick>1649327158</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="79" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="77" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="70" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[Featured]]></Obj>
<Details ><![CDATA[Featured slide3 Successful]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:58]]></Time>
<TimeTick>1649327158</TimeTick>
<NodeArgs eType="User" icon="9" nRep="80" status="Passed" >
<Disp><![CDATA[Featured]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:58]]></Time>
<TimeTick>1649327158</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Your Store.Back]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:55:58]]></Time>
<TimeTick>1649327158</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="83" >
<Disp><![CDATA[Your Store.Back]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:03]]></Time>
<TimeTick>1649327163</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Canon EOS 5D.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:03]]></Time>
<TimeTick>1649327163</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="86" >
<Disp><![CDATA[Canon EOS 5D.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="85" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:07]]></Time>
<TimeTick>1649327167</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:07]]></Time>
<TimeTick>1649327167</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="90" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:07]]></Time>
<TimeTick>1649327167</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="91" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="89" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="82" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj ><![CDATA[Featured]]></Obj>
<Details ><![CDATA[Featured slide4 Successful]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:07]]></Time>
<TimeTick>1649327167</TimeTick>
<NodeArgs eType="User" icon="9" nRep="92" status="Passed" >
<Disp><![CDATA[Featured]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:07]]></Time>
<TimeTick>1649327167</TimeTick>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Your Store.Back]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:07]]></Time>
<TimeTick>1649327167</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="95" >
<Disp><![CDATA[Your Store.Back]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Your Store.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:10]]></Time>
<TimeTick>1649327170</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="97" >
<Disp><![CDATA[Your Store.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:16]]></Time>
<TimeTick>1649327176</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:16]]></Time>
<TimeTick>1649327176</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="101" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="100" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Your Store.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://demo.opencart.com/<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:34]]></Time>
<TimeTick>1649327194</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="103" >
<Disp><![CDATA[Your Store.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:37]]></Time>
<TimeTick>1649327197</TimeTick>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Add to Cart.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["abs_x", True, 296, 80000]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:37]]></Time>
<TimeTick>1649327197</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="106" >
<Disp><![CDATA[Add to Cart.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Add to Cart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:37]]></Time>
<TimeTick>1649327197</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="108" >
<Disp><![CDATA[Add to Cart.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Add to Cart_2.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["abs_x", True, 661, 80000]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:37]]></Time>
<TimeTick>1649327197</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="110" >
<Disp><![CDATA[Add to Cart_2.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Add to Cart_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:37]]></Time>
<TimeTick>1649327197</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="112" >
<Disp><![CDATA[Add to Cart_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[Add to Cart_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:40]]></Time>
<TimeTick>1649327200</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="113" >
<Disp><![CDATA[Add to Cart_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="105" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="94" status="Passed" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj ><![CDATA[addToCartButton]]></Obj>
<Details ><![CDATA[Add to cart Successful]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:40]]></Time>
<TimeTick>1649327200</TimeTick>
<NodeArgs eType="User" icon="9" nRep="114" status="Passed" >
<Disp><![CDATA[addToCartButton]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:40]]></Time>
<TimeTick>1649327200</TimeTick>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[Your Store.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:40]]></Time>
<TimeTick>1649327200</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="117" >
<Disp><![CDATA[Your Store.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:48]]></Time>
<TimeTick>1649327208</TimeTick>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Details>
<Time><![CDATA[4/7/2022 - 15:56:49]]></Time>
<TimeTick>1649327209</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="121" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="120" status="Passed" >