<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus UFT One" productVer="2021" os="Windows 10" host="vm001"><DocLocation><![CDATA[C:\Users\sfjbs\Desktop\opencart\DataDrivenFramework\Driver\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus UFT One"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[Res110]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Mod_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Mod_2" started.]]></Details>
<Time><![CDATA[4/8/2022 - 11:42:46]]></Time>
<TimeTick>1649398366</TimeTick>
<NodeArgs eType="Transaction" icon="4" nRep="7" nType="Start Transaction" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Mod_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/8/2022 - 11:42:58]]></Time>
<TimeTick>1649398378</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Details>
<Time><![CDATA[4/8/2022 - 11:42:58]]></Time>
<TimeTick>1649398378</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:18]]></Time>
<TimeTick>1649398398</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Your Store.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://demo.opencart.com/<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:18]]></Time>
<TimeTick>1649398398</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" >
<Disp><![CDATA[Your Store.Navigate]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="13" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Your Store_2]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:20]]></Time>
<TimeTick>1649398400</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:20]]></Time>
<TimeTick>1649398400</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[WebElement.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:20]]></Time>
<TimeTick>1649398400</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" >
<Disp><![CDATA[WebElement.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[WebElement_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:20]]></Time>
<TimeTick>1649398400</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" >
<Disp><![CDATA[WebElement_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[WebElement_3.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:20]]></Time>
<TimeTick>1649398400</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" >
<Disp><![CDATA[WebElement_3.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[WebElement_4.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:20]]></Time>
<TimeTick>1649398400</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" >
<Disp><![CDATA[WebElement_4.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[WebElement_4.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:20]]></Time>
<TimeTick>1649398400</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" >
<Disp><![CDATA[WebElement_4.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="17" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="16" >
<Disp><![CDATA[Your Store_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj ><![CDATA[addToWishlist]]></Obj>
<Details ><![CDATA[Add to wishlist Successful]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:20]]></Time>
<TimeTick>1649398400</TimeTick>
<NodeArgs eType="User" icon="9" nRep="26" status="Passed" >
<Disp><![CDATA[addToWishlist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:23]]></Time>
<TimeTick>1649398403</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Your Store.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:23]]></Time>
<TimeTick>1649398403</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="29" >
<Disp><![CDATA[Your Store.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:28]]></Time>
<TimeTick>1649398408</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:28]]></Time>
<TimeTick>1649398408</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="33" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="32" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA["Your Store"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:49]]></Time>
<TimeTick>1649398429</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="34" status="Warning" >
<Disp><![CDATA["Your Store"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA["Your Store"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>title=Your Store<br>name=Your Store<br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br>]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:49]]></Time>
<TimeTick>1649398429</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="35" >
<Disp><![CDATA["Your Store"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Your Store.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://demo.opencart.com/<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:49]]></Time>
<TimeTick>1649398429</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="37" >
<Disp><![CDATA[Your Store.Navigate]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="28" status="Warning" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Your Store_2]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:52]]></Time>
<TimeTick>1649398432</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:52]]></Time>
<TimeTick>1649398432</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[WebElement_5.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:52]]></Time>
<TimeTick>1649398432</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="41" >
<Disp><![CDATA[WebElement_5.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[WebElement_5.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:52]]></Time>
<TimeTick>1649398432</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="42" >
<Disp><![CDATA[WebElement_5.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="40" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="39" >
<Disp><![CDATA[Your Store_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[addToComparebutton]]></Obj>
<Details ><![CDATA[ compare button clicked Successful]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:52]]></Time>
<TimeTick>1649398432</TimeTick>
<NodeArgs eType="User" icon="9" nRep="43" status="Passed" >
<Disp><![CDATA[addToComparebutton]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:57]]></Time>
<TimeTick>1649398437</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:57]]></Time>
<TimeTick>1649398437</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[product comparison.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:57]]></Time>
<TimeTick>1649398437</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="47" >
<Disp><![CDATA[product comparison.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[product comparison.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:58]]></Time>
<TimeTick>1649398438</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="48" >
<Disp><![CDATA[product comparison.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="46" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="45" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA[ProductComp]]></Obj>
<Details ><![CDATA[ Product comparision page displayed Successful]]></Details>
<Time><![CDATA[4/8/2022 - 11:43:58]]></Time>
<TimeTick>1649398438</TimeTick>
<NodeArgs eType="User" icon="9" nRep="49" status="Passed" >
<Disp><![CDATA[ProductComp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/8/2022 - 11:44:19]]></Time>
<TimeTick>1649398459</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA["Your Store"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[4/8/2022 - 11:44:19]]></Time>
<TimeTick>1649398459</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="51" status="Warning" >
<Disp><![CDATA["Your Store"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA["Your Store"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>title=Your Store<br>name=Your Store<br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br>]]></Details>
<Time><![CDATA[4/8/2022 - 11:44:19]]></Time>
<TimeTick>1649398459</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="52" >
<Disp><![CDATA["Your Store"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA["Your Store"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[4/8/2022 - 11:44:40]]></Time>
<TimeTick>1649398480</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="53" status="Warning" >
<Disp><![CDATA["Your Store"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA["Your Store"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>title=Your Store<br>name=Your Store<br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br>]]></Details>
<Time><![CDATA[4/8/2022 - 11:44:40]]></Time>
<TimeTick>1649398480</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="54" >
<Disp><![CDATA["Your Store"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Your Store.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2022 - 11:44:40]]></Time>
<TimeTick>1649398480</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="56" >
<Disp><![CDATA[Your Store.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/8/2022 - 11:44:46]]></Time>
<TimeTick>1649398486</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Details>
<Time><![CDATA[4/8/2022 - 11:44:46]]></Time>
<TimeTick>1649398486</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="60" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="59" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA["Your Store"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[4/8/2022 - 11:45:06]]></Time>
<TimeTick>1649398506</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="61" status="Warning" >
<Disp><![CDATA["Your Store"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA["Your Store"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>title=Your Store<br>name=Your Store<br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br>]]></Details>
<Time><![CDATA[4/8/2022 - 11:45:06]]></Time>
<TimeTick>1649398506</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="62" >
<Disp><![CDATA["Your Store"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Your Store.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://demo.opencart.com/<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[4/8/2022 - 11:45:06]]></Time>
<TimeTick>1649398506</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="64" >
<Disp><![CDATA[Your Store.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/8/2022 - 11:45:10]]></Time>
<TimeTick>1649398510</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[WebElement.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2022 - 11:45:10]]></Time>
<TimeTick>1649398510</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="67" >
<Disp><![CDATA[WebElement.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[WebElement_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2022 - 11:45:13]]></Time>
<TimeTick>1649398513</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="69" >
<Disp><![CDATA[WebElement_2.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="66" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Your Store.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/8/2022 - 11:45:16]]></Time>
<TimeTick>1649398516</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="71" >
<Disp><![CDATA[Your Store.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Mod_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Mod_2" ended with "Pass" status (Total Duration: 157.0965 sec Wasted Time: 103.6007 sec).]]></Details>
<Time><![CDATA[4/8/2022 - 11:45:24]]></Time>
<TimeTick>1649398524</TimeTick>
<NodeArgs eType="Transaction" icon="12" nRep="72" nType="End Transaction" Source="Action1" SourceLine="95" >
<Disp><![CDATA[Mod_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="50" status="Warning" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="4/8/2022 - 11:42:46" eTime="4/8/2022 - 11:45:24" passed="6" failed="0" warnings="4" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Warning" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T50">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="4/8/2022 - 11:45:24" eTime="4/8/2022 - 11:45:24" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="74" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T51">
<AName><![CDATA[Action3]]></AName>
<Summary sTime="4/8/2022 - 11:45:24" eTime="4/8/2022 - 11:45:24" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="76" >
<Disp><![CDATA[Action3 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="4/8/2022 - 11:42:42" eTime="4/8/2022 - 11:45:24" passed="6" failed="0" warnings="4" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Warning" >
<Disp><![CDATA[Test Driver Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>