<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus UFT One" productVer="2021" os="Windows 10" host="vm001"><DocLocation><![CDATA[C:\Users\sfjbs\Desktop\opencart\DataDrivenFramework\Driver\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus UFT One"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[Res52]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/6/2022 - 15:41:40]]></Time>
<TimeTick>1649239900</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Details>
<Time><![CDATA[4/6/2022 - 15:41:40]]></Time>
<TimeTick>1649239900</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="10" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="9" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/6/2022 - 15:41:44]]></Time>
<TimeTick>1649239904</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA["Your Store"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (3 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (3 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Your Store<SPAN class=Failed> (Skipped)</SPAN><br>title=Your Store<SPAN class=Failed> (Skipped)</SPAN><br>openurl=https://demo.opencart.com<SPAN class=Failed> (Skipped)</SPAN><br>opentitle=Your Store<SPAN class=Failed> (Skipped)</SPAN><br>openedbytestingtool=0<SPAN class=passed> (Used</SPAN>, 3 matches)</SPAN><br>number of tabs=1<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>]]></Details>
<Time><![CDATA[4/6/2022 - 15:41:44]]></Time>
<TimeTick>1649239904</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" >
<Disp><![CDATA["Your Store"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Your Store.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://demo.opencart.com/<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[4/6/2022 - 15:41:44]]></Time>
<TimeTick>1649239904</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="14" >
<Disp><![CDATA[Your Store.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/6/2022 - 15:41:49]]></Time>
<TimeTick>1649239909</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[iPhone 6.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:41:50]]></Time>
<TimeTick>1649239910</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" >
<Disp><![CDATA[iPhone 6.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="16" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/6/2022 - 15:41:50]]></Time>
<TimeTick>1649239910</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:41:50]]></Time>
<TimeTick>1649239910</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="21" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="20" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Your Store.Back]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:41:55]]></Time>
<TimeTick>1649239915</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="23" >
<Disp><![CDATA[Your Store.Back]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Your Store.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:41:58]]></Time>
<TimeTick>1649239918</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="25" >
<Disp><![CDATA[Your Store.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:04]]></Time>
<TimeTick>1649239924</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:04]]></Time>
<TimeTick>1649239924</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="29" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="28" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA["Your Store"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (3 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (3 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Your Store<SPAN class=Failed> (Skipped)</SPAN><br>title=Your Store<SPAN class=Failed> (Skipped)</SPAN><br>openurl=https://demo.opencart.com<SPAN class=Failed> (Skipped)</SPAN><br>opentitle=Your Store<SPAN class=Failed> (Skipped)</SPAN><br>openedbytestingtool=0<SPAN class=passed> (Used</SPAN>, 3 matches)</SPAN><br>number of tabs=1<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:09]]></Time>
<TimeTick>1649239929</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="30" >
<Disp><![CDATA["Your Store"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Your Store.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://demo.opencart.com/<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:09]]></Time>
<TimeTick>1649239929</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="32" >
<Disp><![CDATA[Your Store.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:12]]></Time>
<TimeTick>1649239932</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[WebElement_3.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:12]]></Time>
<TimeTick>1649239932</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="35" >
<Disp><![CDATA[WebElement_3.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[WebElement_4.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:13]]></Time>
<TimeTick>1649239933</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="37" >
<Disp><![CDATA[WebElement_4.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="34" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Your Store.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:13]]></Time>
<TimeTick>1649239933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="39" >
<Disp><![CDATA[Your Store.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:18]]></Time>
<TimeTick>1649239938</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:18]]></Time>
<TimeTick>1649239938</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="43" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="42" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA["Your Store"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (3 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (3 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Your Store<SPAN class=Failed> (Skipped)</SPAN><br>title=Your Store<SPAN class=Failed> (Skipped)</SPAN><br>openurl=https://demo.opencart.com<SPAN class=Failed> (Skipped)</SPAN><br>opentitle=Your Store<SPAN class=Failed> (Skipped)</SPAN><br>openedbytestingtool=0<SPAN class=passed> (Used</SPAN>, 3 matches)</SPAN><br>number of tabs=1<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:21]]></Time>
<TimeTick>1649239941</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="44" >
<Disp><![CDATA["Your Store"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Your Store.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://demo.opencart.com/<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:23]]></Time>
<TimeTick>1649239943</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="46" >
<Disp><![CDATA[Your Store.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:26]]></Time>
<TimeTick>1649239946</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[MacBook.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:26]]></Time>
<TimeTick>1649239946</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="49" >
<Disp><![CDATA[MacBook.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="48" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:31]]></Time>
<TimeTick>1649239951</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:31]]></Time>
<TimeTick>1649239951</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="53" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="52" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Your Store.Back]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:31]]></Time>
<TimeTick>1649239951</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="55" >
<Disp><![CDATA[Your Store.Back]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:37]]></Time>
<TimeTick>1649239957</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[iPhone.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:37]]></Time>
<TimeTick>1649239957</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="58" >
<Disp><![CDATA[iPhone.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="57" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:41]]></Time>
<TimeTick>1649239961</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:41]]></Time>
<TimeTick>1649239961</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="62" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="61" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Your Store.Back]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:41]]></Time>
<TimeTick>1649239961</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="64" >
<Disp><![CDATA[Your Store.Back]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:46]]></Time>
<TimeTick>1649239966</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Apple Cinema 30'.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:46]]></Time>
<TimeTick>1649239966</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="67" >
<Disp><![CDATA[Apple Cinema 30'.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="66" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:50]]></Time>
<TimeTick>1649239970</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:50]]></Time>
<TimeTick>1649239970</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="71" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="70" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Your Store.Back]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:50]]></Time>
<TimeTick>1649239970</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="73" >
<Disp><![CDATA[Your Store.Back]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:55]]></Time>
<TimeTick>1649239975</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Canon EOS 5D.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:55]]></Time>
<TimeTick>1649239975</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="76" >
<Disp><![CDATA[Canon EOS 5D.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="75" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:59]]></Time>
<TimeTick>1649239979</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:59]]></Time>
<TimeTick>1649239979</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="80" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="79" >
<Disp><![CDATA[Samsung Galaxy Tab 10.1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Your Store.Back]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:42:59]]></Time>
<TimeTick>1649239979</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="82" >
<Disp><![CDATA[Your Store.Back]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Your Store.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:43:03]]></Time>
<TimeTick>1649239983</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="84" >
<Disp><![CDATA[Your Store.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/6/2022 - 15:43:09]]></Time>
<TimeTick>1649239989</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Details>
<Time><![CDATA[4/6/2022 - 15:43:09]]></Time>
<TimeTick>1649239989</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="88" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="87" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA["Your Store"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (3 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (3 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Your Store<SPAN class=Failed> (Skipped)</SPAN><br>title=Your Store<SPAN class=Failed> (Skipped)</SPAN><br>openurl=https://demo.opencart.com<SPAN class=Failed> (Skipped)</SPAN><br>opentitle=Your Store<SPAN class=Failed> (Skipped)</SPAN><br>openedbytestingtool=0<SPAN class=passed> (Used</SPAN>, 3 matches)</SPAN><br>number of tabs=1<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>]]></Details>
<Time><![CDATA[4/6/2022 - 15:43:14]]></Time>
<TimeTick>1649239994</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="89" >
<Disp><![CDATA["Your Store"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Your Store.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://demo.opencart.com/<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[4/6/2022 - 15:43:14]]></Time>
<TimeTick>1649239994</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="91" >
<Disp><![CDATA[Your Store.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/6/2022 - 15:43:18]]></Time>
<TimeTick>1649239998</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Add to Cart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:43:18]]></Time>
<TimeTick>1649239998</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="94" >
<Disp><![CDATA[Add to Cart.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Add to Cart_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:43:21]]></Time>
<TimeTick>1649240001</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="96" >
<Disp><![CDATA[Add to Cart_2.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="93" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Your Store.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:43:24]]></Time>
<TimeTick>1649240004</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="98" >
<Disp><![CDATA[Your Store.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/6/2022 - 15:43:29]]></Time>
<TimeTick>1649240009</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Details>
<Time><![CDATA[4/6/2022 - 15:43:29]]></Time>
<TimeTick>1649240009</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="102" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="101" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA["Your Store"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (3 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (3 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Your Store<SPAN class=Failed> (Skipped)</SPAN><br>title=Your Store<SPAN class=Failed> (Skipped)</SPAN><br>openurl=https://demo.opencart.com<SPAN class=Failed> (Skipped)</SPAN><br>opentitle=Your Store<SPAN class=Failed> (Skipped)</SPAN><br>openedbytestingtool=0<SPAN class=passed> (Used</SPAN>, 3 matches)</SPAN><br>number of tabs=1<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>]]></Details>
<Time><![CDATA[4/6/2022 - 15:43:35]]></Time>
<TimeTick>1649240015</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="103" >
<Disp><![CDATA["Your Store"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Your Store.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://demo.opencart.com/<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[4/6/2022 - 15:43:35]]></Time>
<TimeTick>1649240015</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="105" >
<Disp><![CDATA[Your Store.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/6/2022 - 15:43:38]]></Time>
<TimeTick>1649240018</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[WebButton_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/6/2022 - 15:43:38]]></Time>
<TimeTick>1649240018</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="108" >
<Disp><![CDATA[WebButton_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[WebButton_3.Click]]></Obj>